version: '3.8'
services:
  home_assistant:
    container_name: home_assistant
    restart: unless-stopped
    # This image is referenced mostly statically. It updates pretty quickly and has frequent breaking changes. Review the documentation before upgrading.
    #image: homeassistant/home-assistant:2024.2
    image: homeassistant/home-assistant:2024.3
    devices:
      # Pass down the connection to the USB devices into Home Assistant.
      - /dev/ttyUSB0:/dev/ttyUSB0 # Nortek Z-Wave/Zigbee hub stick
      - /dev/ttyUSB1:/dev/ttyUSB1 # USB connection to APC UPS. Monitors the UPS, allows for automatic shutdown 
      - /dev/ttyACM0:/dev/ttyACM0 # Possibly unused
    environment:
      - IMAGE_DIR=/config/image_scans/
      - DOCUMENT_DIR=/config/cifs_backup/
      - PAPERLESS_DIR=/config/scanned_documents/
    volumes:
      - ./home_assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - ./home_assistant/shared:/shared
      - /dev/serial/by-id/:/dev/serial/by-id/
      - scanned_documents:/config/scanned_documents
      - cifs_document_backup:/config/cifs_backup
      - cifs_image_backup:/config/image_scans
    privileged: true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=$DEFAULT_NETWORK"
      - "traefik.http.routers.home_assistant.rule=Host(`home-assistant.$MY_DOMAIN`)"
      - "traefik.http.routers.home_assistant.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.home_assistant.loadbalancer.server.port=8123"
    networks:
      - nut_server
      - $DEFAULT_NETWORK
      - home_assistant_services
    dns:
      - 192.168.0.12

  mosquitto:
    container_name: mosquitto
    restart: unless-stopped
    image: eclipse-mosquitto 
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    network_mode: host

  paperless:
    container_name: paperless
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    user: 0:0
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    security_opt:
      - apparmor=unconfined
    volumes:
      - ./paperless/data:/usr/src/paperless/data
      #- ./paperless/media:/usr/src/paperless/media
      - cifs_home_lab_storage_paperless_media:/usr/src/paperless/media
      - ./paperless/export:/usr/src/paperless/export
      - scanned_documents:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: $DATABASE_HOSTNAME
      PAPERLESS_DBPORT: 3306
      PAPERLESS_DBUSER: $PAPERLESS_DB_USER
      PAPERLESS_DBPASS: $PAPERLESS_DB_PASSWORD
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_URL: https://paperless.$MY_DOMAIN
      PAPERLESS_CONSUMER_RECURSIVE: true
      PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: true
      # The UID and GID of the user used to run paperless in the container. Set this
      # to your UID and GID on the host so that you have write access to the
      # consumption directory.
      USERMAP_UID: 0
      USERMAP_GID: 0
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.paperless.rule=Host(`paperless.$MY_DOMAIN`)"
      - "traefik.http.routers.paperless.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"
    networks:
      - $DEFAULT_NETWORK

  # Currently only used for Paperless, unknown if it can be used elsewhere
  redis:
    container_name: redis
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - ./redis/data:/data
    networks:
      - $DEFAULT_NETWORK

networks:
  traefik_net:
    name: $DEFAULT_NETWORK
    external: true
  home_assistant_services:
    name: home_assistant_services
  nut_server:
    name: nut_server
    external: true

volumes:
  # Used to share documents between home_assistant and paperless
  scanned_documents:

  # Backs up documents to the NAS for more permanent storage
  cifs_document_backup:
    driver_opts:
      type: "cifs"
      o: ${CIFS_NAS_CREDENTIALS}
      device: "//${DATABASE_HOSTNAME}/brian-home/scanner_files"

  cifs_image_backup:
    driver_opts:
      type: "cifs"
      o: ${CIFS_NAS_CREDENTIALS}
      device: "//${DATABASE_HOSTNAME}/brian-home/Media/Pictures/Scans"

  cifs_home_lab_storage_paperless_media:
    driver_opts:
      type: "cifs"
      o: ${CIFS_NAS_CREDENTIALS}
      device: "//${DATABASE_HOSTNAME}/brian-home/home_lab_storage/paperless/media"

  cifs_home_lab_storage_tandoori_media:
    driver_opts:
      type: "cifs"
      o: ${CIFS_NAS_CREDENTIALS}
      device: "//${DATABASE_HOSTNAME}/brian-home/home_lab_storage/tandoori/media"

