services:
  # Password Manager
  bitwarden:
    container_name: bitwarden
    environment:
      DATABASE_URL: ${BITWARDEN_DB_URL}
    image: vaultwarden/server:latest
    restart: always
    volumes:
      - ./data:/data
    labels:
      - "traefik.docker.network=$DEFAULT_NETWORK"
      - "traefik.enable=true"
      - "traefik.http.routers.bitwarden.rule=Host(`bitwarden.$MY_DOMAIN`)"
    networks:
      - $DEFAULT_NETWORK

networks:
  traefik_net:
    name: $DEFAULT_NETWORK
    external: true

