version: '3.8'
services:
  tandoori:
    container_name: tandoori
    image: vabene1111/recipes
    restart: unless-stopped
    volumes:
      - /mnt/nas/home_lab_storage/tandoori/media:/opt/recipes/mediafiles
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=$DEFAULT_NETWORK"
      - "traefik.http.routers.tandoori.rule=Host(`tandoori.$MY_DOMAIN`)"
      - "traefik.http.routers.tandoori.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.tandoori.loadbalancer.server.port=8080"
    networks:
      - $DEFAULT_NETWORK
    environment:
      - SECRET_KEY=$TANDOOR_SECRET
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=$DATABASE_HOSTNAME
      - POSTGRES_PORT=5433
      - POSTGRES_USER=$POSTGRES_TANDOORI_USERNAME
      - POSTGRES_PASSWORD=$POSTGRES_TANDOORI_PASSWORD
      - POSTGRES_DB=tandoori

networks:
  traefik_net:
    name: $DEFAULT_NETWORK
    external: true
