services:
  dev_tools:
    image: corentinth/it-tools:latest
    container_name: dev_tools
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=$DEFAULT_NETWORK"
      - "traefik.http.routers.dev_tools.rule=Host(`dev-tools.$MY_DOMAIN`)"
      - "traefik.http.services.dev_tools.loadbalancer.server.port=80"
    networks:
      - $DEFAULT_NETWORK

networks:
  traefik_net:
    name: $DEFAULT_NETWORK
    external: true

