version: "3.8"
services:
  mosquitto:
    container_name: mosquitto
    restart: unless-stopped
    image: eclipse-mosquitto
    volumes:
      - ./data/config:/mosquitto/config
      - ./data/data:/mosquitto/data
      - ./data/log:/mosquitto/log
      #ports:
      #- "1883:1883"
    network_mode: host

