services:
  mosquitto:
    container_name: mosquitto
    restart: unless-stopped
    image: eclipse-mosquitto
    volumes:
      - ./data/config:/mosquitto/config
      - ./data/data:/mosquitto/data
      - ./data/log:/mosquitto/log
    network_mode: host

