version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      #- ${UPLOAD_LOCATION}:/usr/src/app/upload
      - cifs_photo_backup:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
    depends_on:
      - redis
      - typesense
    restart: always
    networks:
      - immich_net

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - cifs_photo_backup:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - typesense
    restart: always
    networks:
      - immich_net

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - cifs_photo_backup:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - immich_net

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    restart: always
    networks:
      - immich_net

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - tsdata:/data
    restart: always
    networks:
      - immich_net

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always
    networks:
      - immich_net

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:release
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    #logging:
    #  driver: none
    depends_on:
      - immich-server
    restart: always
    networks:
      - traefik_net
      - immich_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.immich.rule=Host(`immich.${MY_DOMAIN}`)"
      - "traefik.http.routers.immich.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.immich.loadbalancer.server.port=8080"

volumes:
  pgdata:
  model-cache:
  tsdata:
  cifs_photo_backup:
    driver_opts:
      type: "cifs"
      o: ${CIFS_NAS_CREDENTIALS}
      device: "//${DB_HOSTNAME}/brian-home/phone_pictures"

networks:
  traefik_net:
    external: true
  immich_net:
    external: false

