version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - cifs_photo_backup:/usr/src/app/upload
      - cifs_home_pictures:/mnt/media/external_library:ro
    env_file:
      - .env
    depends_on:
      - redis
      - typesense
    restart: always
    networks:
      - immich_net

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - cifs_photo_backup:/usr/src/app/upload
      - cifs_home_pictures:/mnt/media/external_library:ro
    env_file:
      - .env
    depends_on:
      - redis
      - typesense
    restart: always
    networks:
      - immich_net

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    networks:
      - immich_net

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always
    networks:
      - immich_net

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always
    networks:
      - immich_net

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always
    networks:
      - immich_net

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always
    networks:
      - immich_net
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.immich.rule=Host(`immich.${MY_DOMAIN}`)"
      - "traefik.http.routers.immich.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.immich.loadbalancer.server.port=8080"

volumes:
  pgdata:
  model-cache:
  tsdata:
  cifs_photo_backup:
    driver_opts:
      type: "cifs"
      o: ${CIFS_NAS_CREDENTIALS}
      device: "//${DB_HOSTNAME}/brian-home/phone_pictures"

  cifs_home_pictures:
    driver_opts:
      type: "cifs"
      o: ${CIFS_NAS_CREDENTIALS}
      device: "//${DB_HOSTNAME}/brian-home/Media/Pictures"

networks:
  immich_net:
    external: false
  traefik_net:
    external: true
