services:
  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    container_name: the_lounge
    #ports:
    #  - 9010:9000
    user: "${UID}:${GID}"
    volumes:
      - ./data:/var/opt/thelounge
    restart: unless-stopped
    
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=$DEFAULT_NETWORK"
      - "traefik.http.routers.irc.rule=Host(`irc.$MY_DOMAIN`)"
      - "traefik.http.services.irc.loadbalancer.server.port=9000"
    networks:
      - $DEFAULT_NETWORK

networks:
  traefik_net:
    name: $DEFAULT_NETWORK
    external: true
