version: "3"
services:
  wquptime_kuma:
    container_name: uptime_kuma
    restart: unless-stopped
    image: louislam/uptime-kuma:latest
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=$DEFAULT_NETWORK"
      - "traefik.http.routers.uptime_kuma.rule=Host(`uptime-kuma.$MY_DOMAIN`)"
      - "traefik.http.routers.uptime_kuma.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.uptime_kuma.loadbalancer.server.port=3001"
    volumes:
      - ./data:/app/data
    dns:
      - ${DATABASE_HOSTNAME}
    networks:
      - $DEFAULT_NETWORK

networks:
  traefik_net:
    name: $DEFAULT_NETWORK
    external: true

