services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3001:3000"
      - "81:80"
      #- "444:443"
    restart: always
    volumes:
      - ./config:/opt/adguardhome/conf
      - ./workdir:/opt/adguardhome/work
