version: '3.8'

services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest
    volumes:
      - "./data:/etc/linkding/data"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - $DEFAULT_NETWORK
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=$DEFAULT_NETWORK"
      - "traefik.http.routers.linkding.rule=Host(`linkding.$MY_DOMAIN`)"
      #- "traefik.http.routers.linkding.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.linkding.loadbalancer.server.port=9090"
networks:
  traefik_net:
    external: true
    name: $DEFAULT_NETWORK
