version: '3'

services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest
    volumes:
      - "./data:/etc/linkding/data"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.linkding.rule=Host(`linkding.setupjustforme.com`)"
      - "traefik.http.routers.linkding.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.linkding.loadbalancer.server.port=9090"
networks:
  traefik_net:
    external: true
