services:
  homer:
    image: b4bz/homer:latest
    restart: always
    container_name: homer
    volumes:
      - ./data:/www/assets
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=$DEFAULT_NETWORK"
      - "traefik.http.routers.homer.rule=Host(`homer.$MY_DOMAIN`)"
      - "traefik.http.services.homer.loadbalancer.server.port=8080"
    networks:
      - $DEFAULT_NETWORK

networks:
  traefik_net:
    name: $DEFAULT_NETWORK
    external: true

