version: "3"
services:
  wyze_bridge:
    container_name: wyze_bridge
    restart: always
    ports:
      - 1935:1935
      - 8554:8554
      - 8888:8888
      - 5000:5000
    image: mrlt8/wyze-bridge:latest
    environment:
      - WYZE_EMAIL=$WYZE_EMAIL
      - WYZE_PASSWORD=$WYZE_PASSWORD
      - ENABLE_AUDIO=true
      - IGNORE_OFFLINE=true
      - FPS_FIX=true
      - QUALITY=HD60
      - NET_MODE=P2P
      - AUDIO_CODEC=aac
      - FRESH_DATA=true
      - SNAPSHOT=API
      - IMG_DIR=/img/
    networks:
      - $DEFAULT_NETWORK

networks:
  traefik_net:
    name: $DEFAULT_NETWORK
    external: true
