version: '3.8'
services:
  home_assistant:
    container_name: home_assistant
    restart: unless-stopped
    # This image is referenced mostly statically. It updates pretty quickly and has frequent breaking changes. Review the documentation before upgrading.
    #image: homeassistant/home-assistant:2024.2
    image: homeassistant/home-assistant:2024.3
    devices:
      # Pass down the connection to the USB devices into Home Assistant.
      - /dev/ttyUSB0:/dev/ttyUSB0 # Nortek Z-Wave/Zigbee hub stick
      - /dev/ttyUSB1:/dev/ttyUSB1 # USB connection to APC UPS. Monitors the UPS, allows for automatic shutdown 
      - /dev/ttyACM0:/dev/ttyACM0 # Possibly unused
    environment:
      - IMAGE_DIR=/config/image_scans/
      - DOCUMENT_DIR=/config/cifs_backup/
      - PAPERLESS_DIR=/config/scanned_documents/
    volumes:
      - ./home_assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - ./home_assistant/shared:/shared
      - /dev/serial/by-id/:/dev/serial/by-id/
      - scanned_documents:/config/scanned_documents
      - /mnt/nas/scanner_files:/config/cifs_backup
      - /mnt/nas/Media/Pictures/Scans:/config/image_scans
    privileged: true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=$DEFAULT_NETWORK"
      - "traefik.http.routers.home_assistant.rule=Host(`home-assistant.$MY_DOMAIN`)"
      - "traefik.http.routers.home_assistant.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.home_assistant.loadbalancer.server.port=8123"
    networks:
      - nut_server
      - $DEFAULT_NETWORK
      - home_assistant_services
    dns:
      - $DATABASE_HOSTNAME

networks:
  traefik_net:
    name: $DEFAULT_NETWORK
    external: true
  home_assistant_services:
    name: home_assistant_services
  nut_server:
    name: nut_server
    external: true

volumes:
  # Used to share documents between home_assistant and paperless
  scanned_documents:
    name: scanned_documents
    external: false

  # Backs up documents to the NAS for more permanent storage

