services:
  ghost:
    container_name: ghost
    image: ghost:5-alpine
    restart: unless-stopped
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: ${DATABASE_HOSTNAME}
      database__connection__user: ${GHOST_DB_USERNAME}
      database__connection__password: ${GHOST_DB_PASSWORD}
      database__connection__database: ghost
      url: "https://blog.$MY_DOMAIN"
      mail__transport: "SMTP"
      mail__options__service: "Gmail"
      mail__options__host: smtp-relay.gmail.com
      mail__options__port: 465
      mail__options__secure: true
      mail__options__auth__user: ${GMAIL_EMAIL}
      mail__options__auth__pass: ${GMAIL_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=$DEFAULT_NETWORK"
      - "traefik.http.routers.ghost.rule=Host(`blog.$MY_DOMAIN`)"
      - "traefik.http.services.ghost.loadbalancer.server.port=2368"
    networks:
      - $DEFAULT_NETWORK

networks:
  traefik_net:
    name: $DEFAULT_NETWORK
    external: true

